# Generated by Django 6.0.5 on 2026-05-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_alter_content_id_alter_empresa_id_alter_estagio_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
