# Generated by Django 4.2.11 on 2026-06-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0006_alter_content_id_alter_content_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='estagio',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='estudante',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='professororientador',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={'ordering': ['-data_envio']},
        ),
        migrations.AlterModelOptions(
            name='supervisorempresa',
            options={'ordering': ['nome']},
        ),
    ]
