@startmindmap
* Sistema de Gestao de Estagios
** Legislacao
*** Lei 11.788/2008
*** MEC
*** Regulamento Interno

** Sistema
*** Cadastro de Estagio
*** Relatorios
*** Controle de Conformidade
*** Alertas

** Usuarios
*** Estudante
*** Professor
*** Supervisor
*** Coordenacao

** Processos
*** Ingresso
*** Acompanhamento
*** Avaliacao

** Tecnologia
*** IA
*** Integracoes
@endmindmap
